services:
  - type: web
    name: telegram-bot
    env: python
    runtime: python
    buildCommand: |
      curl https://pyenv.run | bash
      export PATH="$HOME/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"
      pyenv install 3.11.9
      pyenv global 3.11.9
      python -m pip install --upgrade pip
      python -m pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 8155036128:AAFYCMal39Fa-g-Ri0cjcFb7sN8aUod4RT0
      - key: BOT_USERNAME
        value: LinkVidBot_bot
      - key: CHANNEL_ID
        value: @Movies_bot21
      - key: CHANNEL_INVITE_LINK
        value: https://t.me/Movies_bot21
